[project]
name = "app"
version = "0.1.0"
description = "A FastAPI backend that serves data scraped from vlr.gg"
requires-python = ">=3.12"
authors = [
    { name = "Akhil Narang", email = "me@akhilnarang.dev" }
]
dependencies = [
    "fastapi[all]",
    "httpx",
    "beautifulsoup4",
    "uvicorn[standard]",
    "gunicorn",
    "python-dateutil",
    "firebase-admin",
    "brotli-asgi",
    "sentry-sdk[arq,fastapi,httpx,starlette]",
    "lxml",
    "redis[hiredis]",
    "arq",
    "semver",
    "rich",
]

[tool.uv]
dev-dependencies = [
    "mypy>=1.11.1",
    "types-python-dateutil>=2.9.0.20240821",
    "types-redis>=4.6.0.20240819",
    "ruff>=0.6.2",
]

[tool.ruff]
line-length = 120
exclude = ["__init__.py"]
