[tool.poetry]
name = "vlrgg-scraper"
version = "0.1.0"
description = "A scraper for vlr.gg"
authors = ["Akhil Narang <me@akhilnarang.dev>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.95.0"
httpx = "^0.23.3"
beautifulsoup4 = "^4.12.0"
uvicorn = {extras = ["standard"], version = "^0.21.1"}
gunicorn = "^20.1.0"
python-dateutil = "^2.8.2"
firebase-admin = "^6.1.0"
brotli-asgi = "^1.3.0"
sentry-sdk = {extras = ["arq", "fastapi"], version = "^1.18.0"}
lxml = "^4.9.2"
redis = "^4.5.3"
arq = "^0.25.0"
semver = "^2.13.0"
rich = "^13.3.3"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
isort = "^5.12.0"
mypy = "^1.1.1"
flake8 = "^6.0.0"
autoflake = "^2.0.2"
types-python-dateutil = "^2.8.19.10"
types-redis = "^4.5.3.0"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 120

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
