[tool.poetry]
name = "vlrgg-scraper"
version = "0.1.0"
description = "A scraper for vlr.gg"
authors = ["Akhil Narang <me@akhilnarang.dev>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = {extras = ["all"], version = "^0.104.1"}
httpx = "^0.25.1"
beautifulsoup4 = "^4.12.2"
uvicorn = {extras = ["standard"], version = "^0.24.0"}
gunicorn = "^21.2.0"
python-dateutil = "^2.8.2"
firebase-admin = "^6.2.0"
brotli-asgi = "^1.4.0"
sentry-sdk = {extras = ["arq", "fastapi", "httpx", "starlette"], version = "^1.35.0"}
lxml = "^4.9.3"
redis = {extras = ["hiredis"], version = "^5.0.1"}
arq = "^0.25.0"
semver = "^3.0.2"
rich = "^13.6.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.7.0"
types-python-dateutil = "^2.8.19.14"
types-redis = "^4.6.0.10"
ruff = "^0.1.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
exclude = ["__init__.py"]