[tool.poetry]
name = "vlrgg-scraper"
version = "0.1.0"
description = "A scraper for vlr.gg"
authors = ["Akhil Narang <me@akhilnarang.dev>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = {extras = ["all"], version = "^0.103.0"}
httpx = "^0.24.1"
beautifulsoup4 = "^4.12.2"
uvicorn = {extras = ["standard"], version = "^0.23.2"}
gunicorn = "^21.2.0"
python-dateutil = "^2.8.2"
firebase-admin = "^6.2.0"
brotli-asgi = "^1.4.0"
sentry-sdk = {extras = ["arq", "fastapi"], version = "^1.29.2"}
lxml = "^4.9.3"
redis = "^5.0.0"
arq = "^0.25.0"
semver = "^3.0.1"
rich = "^13.5.2"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
isort = "^5.12.0"
mypy = "^1.5.1"
flake8 = "^6.1.0"
autoflake = "^2.2.0"
types-python-dateutil = "^2.8.19.14"
types-redis = "^4.6.0.5"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 120

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
