[tool.poetry]
name = "vlrgg-scraper"
version = "0.1.0"
description = "A scraper for vlr.gg"
authors = ["Akhil Narang <me@akhilnarang.dev>"]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = {extras = ["all"], version = "^0.110.0"}
httpx = "^0.27.0"
beautifulsoup4 = "^4.12.3"
uvicorn = {extras = ["standard"], version = "^0.27.1"}
gunicorn = "^21.2.0"
python-dateutil = "^2.9.0"
firebase-admin = "^6.4.0"
brotli-asgi = "^1.4.0"
sentry-sdk = {extras = ["arq", "fastapi", "httpx", "starlette"], version = "^1.40.6"}
lxml = "^5.1.0"
redis = {extras = ["hiredis"], version = "^5.0.2"}
arq = "^0.25.0"
semver = "^3.0.2"
rich = "^13.7.1"

[tool.poetry.group.dev.dependencies]
mypy = "^1.8.0"
types-python-dateutil = "^2.8.19.20240106"
types-redis = "^4.6.0.20240218"
ruff = "^0.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
exclude = ["__init__.py"]