[tool.poetry]
name = "vlrgg-scraper"
version = "0.1.0"
description = "A scraper for vlr.gg"
authors = ["Akhil Narang <me@akhilnarang.dev>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.80.0"
httpx = "^0.23.0"
beautifulsoup4 = "^4.11.1"
uvicorn = {extras = ["standard"], version = "^0.18.3"}
gunicorn = "^20.1.0"
python-dateutil = "^2.8.2"
firebase-admin = "^5.2.0"
brotli-asgi = "^1.1.0"
sentry-sdk = {extras = ["fastapi"], version = "^1.9.5"}
lxml = "^4.9.1"
redis = "^4.3.4"
arq = "v0.23a1"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
isort = "^5.10.1"
mypy = "^0.971"
flake8 = "^5.0.4"
autoflake = "^1.4"
types-python-dateutil = "^2.8.19"
types-redis = "^4.3.17"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 120

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
