[tool.poetry]
name = "vlrgg-scraper"
version = "0.1.0"
description = "A scraper for vlr.gg"
authors = ["Akhil Narang <me@akhilnarang.dev>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.88.0"
httpx = "^0.23.1"
beautifulsoup4 = "^4.11.1"
uvicorn = {extras = ["standard"], version = "^0.20.0"}
gunicorn = "^20.1.0"
python-dateutil = "^2.8.2"
firebase-admin = "^6.0.1"
brotli-asgi = "^1.2.0"
sentry-sdk = {extras = ["fastapi"], version = "^1.11.1"}
lxml = "^4.9.2"
redis = "^4.4.0"
arq = "^0.25.0"
semver = "^2.13.0"

[tool.poetry.dev-dependencies]
black = "^22.12.0"
isort = "^5.11.2"
mypy = "^0.991"
flake8 = "^6.0.0"
autoflake = "^2.0"
types-python-dateutil = "^2.8.19"
types-redis = "^4.3.21"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 120

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
