"""Add match_players table and remove player columns from matches

Revision ID: 754dc3b527a6
Revises: e83934a96e1d
Create Date: 2025-10-04 22:18:51.328180

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "754dc3b527a6"
down_revision: Union[str, Sequence[str], None] = "e83934a96e1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "match_players",
        sa.Column("match_id", sa.String(), nullable=False),
        sa.Column("player_id", sa.String(), nullable=False),
        sa.Column("team_id", sa.String(), nullable=False),
        sa.Column("map", sa.String(), nullable=False),
        sa.Column("agents", sa.JSON(), nullable=True),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("acs", sa.Integer(), nullable=True),
        sa.Column("kills", sa.Integer(), nullable=True),
        sa.Column("deaths", sa.Integer(), nullable=True),
        sa.Column("assists", sa.Integer(), nullable=True),
        sa.Column("kast", sa.Integer(), nullable=True),
        sa.Column("adr", sa.Integer(), nullable=True),
        sa.Column("headshot_percent", sa.Integer(), nullable=True),
        sa.Column("first_kills", sa.Integer(), nullable=True),
        sa.Column("first_deaths", sa.Integer(), nullable=True),
        sa.Column("first_kills_diff", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("match_id", "player_id", "map"),
    )
    op.drop_column("matches", "team_a_players")
    op.drop_column("matches", "team_b_players")
    op.create_index("idx_event_title", "events", ["title"], unique=False)
    op.create_index("idx_match_player_match_id", "match_players", ["match_id"], unique=False)
    op.create_index("idx_match_player_player_id", "match_players", ["player_id"], unique=False)
    op.create_index("idx_match_player_team_id", "match_players", ["team_id"], unique=False)
    op.create_index("idx_match_event_id", "matches", ["event_id"], unique=False)
    op.create_index("idx_match_team_a_id", "matches", ["team_a_id"], unique=False)
    op.create_index("idx_match_team_b_id", "matches", ["team_b_id"], unique=False)
    op.create_index("idx_match_time", "matches", ["time"], unique=False)
    op.create_index("idx_player_alias", "players", ["alias"], unique=False)
    op.create_index("idx_player_team_id", "players", ["team_id"], unique=False)
    op.create_index("idx_team_normalized_name", "teams", ["normalized_name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_team_normalized_name", table_name="teams")
    op.drop_index("idx_player_team_id", table_name="players")
    op.drop_index("idx_player_alias", table_name="players")
    op.drop_index("idx_match_time", table_name="matches")
    op.drop_index("idx_match_team_b_id", table_name="matches")
    op.drop_index("idx_match_team_a_id", table_name="matches")
    op.drop_index("idx_match_event_id", table_name="matches")
    op.drop_index("idx_match_player_team_id", table_name="match_players")
    op.drop_index("idx_match_player_player_id", table_name="match_players")
    op.drop_index("idx_match_player_match_id", table_name="match_players")
    op.drop_index("idx_event_title", table_name="events")
    op.add_column("matches", sa.Column("team_b_players", sa.JSON(), nullable=True))
    op.add_column("matches", sa.Column("team_a_players", sa.JSON(), nullable=True))
    op.drop_table("match_players")
    # ### end Alembic commands ###
