"""Initial migration with Team, Player, Match, Event models (including player_type)

Revision ID: e83934a96e1d
Revises:
Create Date: 2025-10-03 21:35:25.328953

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e83934a96e1d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("prize", sa.String(), nullable=True),
        sa.Column("dates", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("img", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("normalized_name", sa.String(), nullable=False),
        sa.Column("tag", sa.String(), nullable=True),
        sa.Column("img", sa.String(), nullable=True),
        sa.Column("website", sa.String(), nullable=True),
        sa.Column("twitter", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("region", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("normalized_name"),
    )
    op.create_table(
        "event_teams",
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("team_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("event_id", "team_id"),
    )
    op.create_table(
        "matches",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("team_a_id", sa.String(), nullable=True),
        sa.Column("team_b_id", sa.String(), nullable=True),
        sa.Column("event_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("time", sa.DateTime(), nullable=True),
        sa.Column("series", sa.String(), nullable=True),
        sa.Column("event_name", sa.String(), nullable=True),
        sa.Column("team_a_players", sa.JSON(), nullable=True),
        sa.Column("team_b_players", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_a_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_b_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "players",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("alias", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("player_type", sa.String(), nullable=True),
        sa.Column("img", sa.String(), nullable=True),
        sa.Column("team_id", sa.String(), nullable=True),
        sa.Column("twitch", sa.String(), nullable=True),
        sa.Column("twitter", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("total_winnings", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("players")
    op.drop_table("matches")
    op.drop_table("event_teams")
    op.drop_table("teams")
    op.drop_table("events")
    # ### end Alembic commands ###
