on:
  push:
    branches:
      - master

name: Build and push docker image to container registry
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to container registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username akhilnarang --password-stdin
      - name: Build and push image
        run: docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/akhilnarang/vlrgg-scraper:master . --push
